name: Node.js CI

on:
  pull_request:
    branches: ["dev/v2"]
  push:
    branches: ["dev/v2"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install deps
        run: |
          export NODE_OPTIONS="--max-old-space-size=512"
          npm ci --prefer-offline --no-audit --no-fund
